### ISSUE TITLE
Control tetromino with keyboard

### ISSUE THREAD

**Issue by dealingwith** [MinecraftU/2021-computer-adventures#14]

**Comment by jamespeilunli** [comment]
Uh oh... the on method doesn't work either ([reference](https://github.com/MinecraftU/2021-computer-adventures/issues/12#issuecomment-889355181))...

This code:
```
    def move
        on :key_down do |event|
            [code]
        end
    end
```
throws:
```
/home/jamesli/github_repos/2021-computer-adventures/tetrominos.rb:32:in `move': undefined method `on' for #<Tetromino:0x000055b4456bd678> (NoMethodError)
```
and previous code except with a $ before on throws:
```
/home/jamesli/github_repos/2021-computer-adventures/tetris.rb:3:in `require_relative': /home/jamesli/github_repos/2021-computer-adventures/tetrominos.rb:32: syntax error, unexpected ':', expecting `end' (SyntaxError)
        $on :key_down do |event|
            ^
```
```
