### ISSUE TITLE
Document dependency managment

### ISSUE THREAD

**Issue by dealingwith** [MinecraftU/2021-computer-adventures#7]

**Comment by dealingwith** [comment]
@jamespeilunli I need the name of that 2D library again. It would be most helpful if you went ahead and pushed a branch with your experiments from the weekend.

**Comment by jamespeilunli** [comment]
The library is called [rubygame](https://rubygems.org/gems/rubygame). To install it you will need SDL; [this](https://stackoverflow.com/a/17572105/16191068) should have all the packages you need before running `sudo gem install rubygame`. There is a good basic tutorial on it [here](https://lorenzod8n.wordpress.com/2007/12/09/rubygame-tutorial-1-getting-started/).

What do you mean by my experiments from the weekend?

**Comment by jamespeilunli** [comment]
It has a wiki on its GitHub for installing: https://github.com/rubygame/rubygame/wiki/Mac-Install-Guide

**Comment by dealingwith** [comment]
I created a Gemfile and `bundle install` installed `rubygame` and all its dependencies:

```
Using rake 13.0.6
Using bundler 2.1.2
Using ffi 1.15.3
Using nice-ffi 0.4
Using ruby-sdl-ffi 0.4
Using rubygame 2.6.4
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

But then when I try to run `tetris.rb` via `bundle exec ruby tetris.rb`

```
Traceback (most recent call last):
	15: from tetris.rb:1:in `<main>'
	14: from tetris.rb:1:in `require'
	13: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubygame-2.6.4/lib/rubygame.rb:43:in `<top (required)>'
	12: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubygame-2.6.4/lib/rubygame.rb:43:in `each'
	11: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubygame-2.6.4/lib/rubygame.rb:44:in `block in <top (required)>'
	10: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubygame-2.6.4/lib/rubygame.rb:44:in `require'
	 9: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubygame-2.6.4/lib/rubygame/main.rb:22:in `<top (required)>'
	 8: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rubygame-2.6.4/lib/rubygame/main.rb:22:in `require'
	 7: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl.rb:79:in `<top (required)>'
	 6: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl.rb:79:in `each'
	 5: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl.rb:80:in `block in <top (required)>'
	 4: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl.rb:80:in `require'
	 3: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl/mac.rb:49:in `<top (required)>'
	 2: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl/mac.rb:153:in `<module:Mac>'
	 1: from /Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-sdl-ffi-0.4/lib/ruby-sdl-ffi/sdl/mac.rb:161:in `<module:ObjC>'
/Users/danielmiller/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.15.3/lib/ffi/library.rb:393:in `callback': callbacks cannot have variadic parameters (ArgumentError)
```
